### ISSUE TITLE
Build Failed: [Errno2] No such file or directory

### ISSUE THREAD

**Issue by zolotas4** [AdaCore/libadalang#1]
Trying to build the libadalang by running the sudo python ada/manage.py build I get the following error:

`Build Failed: [Errno2] No such file or directory`

I have downloaded and installed gnat ada 2012 from libre ada and quex 0.65.4

**Comment by pmderodat** [comment]
Hi!

I can reproduce this if I remove GPRbuild from my `PATH`, so I assume you don’t have properly installed a GNAT release. What release have you installed exactly? (is “GNAT Ada 2012” actually GNAT GPL 2012 as downloaded from libre.adacore.com?) For the record, I just checked: Libadalang builds fine with GNAT GPL 2016. Maybe: how have you installed it?

You can check if GPRbuild is available with the following command:

```sh
$ which gprbuild
# When GPRbuild is not properly installed:
#     which: no gprbuild in (/usr/local/bin:/usr/bin:…)
# When GPRbuild is properly installed:
#     /path/to/your/installed/gprbuild
```

Now, the error message you quoted is not very helpful, sorry for that! I have enhanced the `manage.py` machinery to be more explicit (https://github.com/AdaCore/langkit/commit/debbecd112c001e088c8c7226ca63c71f44206c3). Now I have:

```
Build failed: error while running gprbuild -m -p -j8 -P…/build/lib/gnat/libadalang.gpr -XBUILD_MODE=dev -XLIBADALANG_WARNINGS=true -XLIBRARY_TYPE=relocatable -cargs:
    [Errno 2] No such file or directory
```

Which is not yet ideal, but at least it gives a clue about what went wrong.

**Comment by zolotas4** [comment]
Hi! Thanks for the reply.

`$which gprbuild` returns `$/usr/local/gnat/bin/gprbuild` 
`$echo $PATH` returns `...:/usr/local/gnat/bin:...`

Isn't those appropriate? I rerun the setup with your updated exception I know get this:

`libadalang.gpr:2:06: unknown project file: "gnatcoll"
libadalang.gpr:3:06: unknown project file: "gnatcoll_iconv"
libadalang.gpr:133:18: variable "target" is not typed
libadalang.gpr:134:21: illegal case label "x86-linux"
gprbuild: "/Users/Thanos/Documents/libadalang/build/lib/gnat/libadalang.gpr" processing failed
Build failed: error while running gprbuild -m -p -j4 -P/Users/Thanos/Documents/libadalang/build/lib/gnat/libadalang.gpr -XBUILD_MODE=dev -XLIBADALANG_WARNINGS=true -XLIBRARY_TYPE=relocatable -cargs:
    Command '['gprbuild', '-m', '-p', '-j4', '-P/Users/Thanos/Documents/libadalang/build/lib/gnat/libadalang.gpr', '-XBUILD_MODE=dev', '-XLIBADALANG_WARNINGS=true', '-XLIBRARY_TYPE=relocatable', '-cargs']' returned non-zero exit status 4`

**Comment by pmderodat** [comment]
Ah, OK. :-) Your last error message actually confirms that the toolchain is properly installed: it’s GPRbuild that says “unknown project file”. Note that I advise to stick with the 2016 release as Libadalang’s development uncovered several issues that has been fixed in this release.

Now, the following error message:
```
libadalang.gpr:2:06: unknown project file: "gnatcoll"
libadalang.gpr:3:06: unknown project file: "gnatcoll_iconv"
```
Indicates that [GNATcoll](https://github.com/AdaCore/gnatcoll), which Libadalang depends on, is not installed. I realize we haven’t properly documented this dependency so I’ll update the README. I recommand to build and install the `gpl-2016` branch, which I’ve used successfully tested (https://github.com/AdaCore/gnatcoll/tree/gpl-2016). Bottom line:
```sh
$ git clone https://github.com/AdaCore/gnatcoll.git -b gpl-2016
$ cd gnatcoll
$ ./configure --prefix=/usr/local
$ make
$ make install
```
Now that GNATcoll is installed, these two errors should go away. Now, the next one:
```
libadalang.gpr:133:18: variable "target" is not typed
```
bugs me, and in my opinion the other ones are related to the same issue. I just can’t reproduce it and the wording makes me wonder if you are still the GPRbuild from the GPL 2012 release. You can find out which one is running this way (plus, here’s what I get):
```
$ gprbuild --version
GPRBUILD GPL 2016 (20160515) (x86_64-pc-linux-gnu)
Copyright (C) 2004-2016, AdaCore
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Can you check?

**Comment by zolotas4** [comment]
Thanks for the help. The problem has been solved with your latest comments. Really appreciated.

**Comment by pmderodat** [comment]
Awesome, thank you for the feedback!
