### ISSUE TITLE
misleading readme

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/libadalang#12]
I avoided packaging libadalang for a long time because of this line:
```
Libadalang is still pre-alpha software! None of its APIs are stable, the shape of the abstract syntax tree is not yet stable, and most of its features are either not stable or not fully implemented.
```

Recently, I discovered that GPS 2017 required it and was forced to import "pre-alpha" software.  I'm guessing that because it's used in production software, libadalang is no longer "pre-alpha".

It's my opinion this line is damaging if it's not true.  I know it affected my decisions.  I would recommend updating this line ASAP.  It's unfortunate that it made it into branch gpl-2017.

**Comment by pmderodat** [comment]
Hello again @jrmarino,

Libadalang is still “pre-alpha” and GPS 2017’s dependency on it is peculiar. First some context: Ada-aware features in GPS has been implemented with custom code from the beginning. The aim of Libadalang is to give a “complete” and most importantly tool-agnostic set of such Ada-aware features.

Now Libadalang’s development is a huge task, that takes time. Integrating LAL in GPS will also take time, so to parallelize work we started to do it even though LAL still has no stable release. Because of this, GPS’s use of LAL is disabled by default. So unless some experimental setting is enabled, LAL’s “unstability” does not affect GPS, which *is* supposed to be stable.

And here we are: GPS 2017, a stable release, dependends on LAL, which has no stable release yet. And it should be fine for GPS users. In the end, if some README/documentation should be adjusted, I think it should be in GPS’s release notes, don’t you think? As I said, LAL still has no stable release.

**Comment by jrmarino** [comment]
if it's disabled by default, that mechanism is broken.
My compilation broke because it couldn't find lal.gpr. 
I couldn't find a setting to disable adalang.  When I saw it was included in the windows binary release, I had to assume libadalang was required.

bottom line: I initially tried to build GPS without libadalang and it failed.  It was only when I added libadalang to the port that it was able to successfully build.  Thus, it is *not* disabled by default (or it's not *correctly* disabled)

**Comment by pmderodat** [comment]
The switch to enable/disable LAL in GPS happens at runtime: in order to build GPS 2017, LAL is always required.

**Comment by jrmarino** [comment]
I think the README should be clarified to say, that it is a build requirement of GPS even though it's in such an early stage in development.  I never would have packaged libadalang with the "pre-alpha" lable unless it was clear that it was a legit dependency.

GPS has a list of requirements and libadalang is missing from that list, adding to the initial confusion.  That list (located in one of the INSTALL/README-type files) should also be updated to include libadalang.  So I would say both places need updating.

**Comment by raph-amiard** [comment]
Hello jrmarino,

> I think the README should be clarified to say, that it is a build requirement of GPS even though it's in such an early stage in development. I never would have packaged libadalang with the "pre-alpha" lable unless it was clear that it was a legit dependency.

It is very clearly explained in what capacity LAL is not yet stable. What I might be OK to do is to say "you might find LAL used in other AdaCore products internally" or something of the sort. I'll try to find some wording.

> GPS has a list of requirements and libadalang is missing from that list, adding to the initial confusion. That list (located in one of the INSTALL/README-type files) should also be updated to include libadalang. So I would say both places need updating.

Good catch, I'll relay this to the GPS team !
