### ISSUE TITLE
Fuzzing - libadalang-sources.adb:40 range check failed

### ISSUE THREAD

**Issue by touisteur** [AdaCore/libadalang#14]
Hi,

I'm doing some experiments on fuzzing libadalang, to see how robust the parser is.

I use the "parse" main program : 

> parse -C -P -f my_file

and am trying to trigger a top-level (uncaught) exception.

I have some test cases that trigger a constraint error at libadalang-sources.adb:40 range check failed.

The sha-1 I'm testing against : f5a3ba0b7755 .

Test cases are attached here [ticket-constraint-error-libadalang-sources-40.zip](https://github.com/AdaCore/libadalang/files/1432430/ticket-constraint-error-libadalang-sources-40.zip)

**Comment by raph-amiard** [comment]
Hello Touisteur !

Thank you very much for the bug reports :+1: (This one and the other one) We won't fix them right away because they're not high on our priority list, but we will fix them eventually :)

**Comment by pmderodat** [comment]
Hello @touisteur,

As Raphaël said, thank you very much for your bug reports. :-) The bug that you saw here was due to our processing of brackets encoding (`["deadbeef"]`) which did not integrate properly with our error reporting engine. This is now (as of https://github.com/AdaCore/libadalang/commit/dbf6ec8e15235204e34ebfec5fdd4870e4e76feb and https://github.com/AdaCore/langkit/commit/0efd6708f002577b9cc3b0095301d98d33a004c0) implemented: the uncaught exceptions are gone and you have instead a nice (?) error message. For instance:

```sh
$ parse -s -f id\:000001\,sig\:06\,src\:000035\,op\:flip1\,pos\:94 
id:000001,sig:06,src:000035,op:flip1,pos:94: 4:4: invalid brackets encoding
```

**Comment by touisteur** [comment]
Hi @pmderodat,

thanks for the feedback. 

BR
Lionel
