### ISSUE TITLE
Fuzzing - exception at gnatcoll-iconv.adb:116 with incorrect input

### ISSUE THREAD

**Issue by touisteur** [AdaCore/libadalang#15]
Hi, I'm trying to fuzz the libadalang parser, and found a (very simple) case that if launched with the "parse" main program (parse -C -P -f my_file), breaks with a constraint error at :
> gnatcoll-iconv.adb:116:44 index check failed index 3 not in 1..2

The example (very simple) is attached here : [libadalang-parse-gnat-icoll-constraint-error.zip](https://github.com/AdaCore/libadalang/files/1432438/libadalang-parse-gnat-icoll-constraint-error.zip)

Of course, it's not valid code and it's an extreme case (that's what you get with fuzzing)... If you try to open it in some file editors, it will look empty. According to wc -c there are two characters, and according to "less" they are : `<FE><FF>`

The sha-1 I'm testing against : f5a3ba0b7755 .

**Comment by pmderodat** [comment]
Hello again,

Thank you for reporting this! The uncaught exception is due to the fact that:

* `GNATCOLL.Iconv` does not support an empty input string to decode;
* Libadalang used to decode [BOMs](https://en.wikipedia.org/wiki/Byte_order_mark) after it checked for empty input strings.

As a result, a source file that just contained a BOM and nothing else after passed our null input check and then yielded an empty string to `GNATCOLL.Iconv`. The https://github.com/AdaCore/langkit/commit/0efd6708f002577b9cc3b0095301d98d33a004c0 commit fixes this, so the crash you saw should now be gone:

```sh
$ parse -f libadalang-parse-gnat-icoll-constraint-error 
CompilationUnitList[1:1-1:1]: <empty list>
```

**Comment by touisteur** [comment]
Hi @pmderodat @raph-amiard , 

thanks for the correction and the feedback.

Cheers :-)

**Comment by pmderodat** [comment]
You are welcome! :-)
