### ISSUE TITLE
Public API for name resolution results

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/libadalang#21]
For the moment we have a - sub-optimal, not really documented API - for name resolution results, namely:

`p_ref_val` is a property callable on any node, that will return the referenced declaration if applicable.
`p_type_val` is a property callable on expressions, that will return the type of the expression.

The problem is that for those to work, for the moment the user needs to first call resolve_names on the closest parent that is a complete context for name resolution.

Opening this issue with following goals:

- Call resolve_names automatically
- Rename `p_ref_val` into `p_referenced_decl`
- Rename `p_type_val` into `p_type`

**Comment by raph-amiard** [comment]
@pmderodat This is mostly done, but there is a bug in name resolution. See branch https://github.com/AdaCore/libadalang/tree/topic/nameres_papi for the current state / reproducer.

You can see the problem by running the name_resolution part of the test suite

**Comment by pmderodat** [comment]
@raph-amiard It seems that the `Property_Error` you saw in name resolution is actually due to an infinite recursion in properties. I’ve patched Langkit so that this exception clearly states in its message that an infinite recursion is going on. See <https://github.com/AdaCore/langkit/commit/f9588be6c35828b79b02df6d4b47e1568d73184c> and <https://github.com/AdaCore/langkit/commit/63695db7c341de84c93ed2cdae25d9236cf71300>.

**Comment by raph-amiard** [comment]
Thanks @pmderodat !

**Comment by raph-amiard** [comment]
One last issue for that is to make Populate_Lexical_Env called automatically. This will be handled by @pmderodat  on the langkit side. @pmderodat I'll put you in the assignees for this issue while it's waiting on that !

**Comment by raph-amiard** [comment]
This is done, thanks PM!
