### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by forsyth** [AdaCore/libadalang#287]
Towards the end of trying to build the current libadalang, I get the following:

Building the generated source code
Setup
   [mkdir]        object directory for project Langkit_Support
   [mkdir]        library directory for project Langkit_Support
   [mkdir]        object directory for project Libadalang
   [mkdir]        library directory for project Libadalang
Compile
   [Ada]          langkit_support-adalog-main_support.adb
   [Ada]          langkit_support-adalog-unify_one_side.adb
   [Ada]          langkit_support-iterators.adb
   [Ada]          langkit_support-text.adb
   [Ada]          langkit_support-lexical_env.adb
langkit_support-text.adb:28:14: warning: license of withed unit "GNATCOLL.Iconv" may be inconsistent

   compilation of langkit_support-text.adb failed

gprbuild: *** compilation phase failed
Build failed: error while running gprbuild -p -j4 -P/tmp/libadalang/build/lib/gnat/libadalang.gpr -XBUILD_MODE=dev -XLIBRARY_TYPE=relocatable -XGPR_BUILD=relocatable -XXMLADA_BUILD=relocatable -XLIBADALANG_WARNINGS=true:
    Command '['gprbuild', '-p', '-j4', '-P/tmp/libadalang/build/lib/gnat/libadalang.gpr', '-XBUILD_MODE=dev', '-XLIBRARY_TYPE=relocatable', '-XGPR_BUILD=relocatable', '-XXMLADA_BUILD=relocatable', '-XLIBADALANG_WARNINGS=true']' returned non-zero exit status 4

Is it really the licence difference that's failing? there wasn't any other diagnostic. What does LIBADALANG_WARNINGS=true do? I can find the value set at various places, but not where it is used.

**Comment by pmderodat** [comment]
The `LIBADALANG_WARNINGS` enviornement variable controls the compilation switches the project files passes to the compiler. It is defined [here](https://github.com/AdaCore/langkit/blob/master/langkit/templates/project_file.mako#L20) and used [here](https://github.com/AdaCore/langkit/blob/master/langkit/templates/project_file.mako#L118).

In your case, GNAT complains most likely because the sources of Libadalang built from GitHub (GPLv3 + exception) are used with the GNATCOLL shipped with GNAT Community (GPLv3, no exception). We recommend to re-build LibGPR and GNATCOLL from GitHub sources, just like we do in our [Travis CI script](https://github.com/AdaCore/libadalang/blob/master/utils/travis-install.sh): this way you will get consistent licenses.
