### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by briot** [AdaCore/libadalang#325]
Although this was briefly mentioned in #254, I did not see a specific issue dedicated to making libadalang compatible with python3

We finally decided to port our scripts to python3. Unfortunately, our libadalang tool to generate i/o support for Ada types depends on some of these scripts, but libadalang is not compatible with python3. So I am looking into the best approach here.

In #254, you mentioned support for python3 would be "soon-ish". Is this work in progress already ? Or perhaps asking for patches (which I do not have yet, but I could perhaps look into that).

Thanks
Manu

**Comment by raph-amiard** [comment]
Hello Manu! Support for python 3 is definitely in our roadmap for the next release, and (although this is no hard promise :)) we plan to start working on it soon after 20.0 is out.

Porting libadalang.py is one of the easiest things on our path I think, and it's the most client critical, with the end of support for Python 2. Ideally we'd like to keep it 2 and 3 compatible, because I envision a lot of users not ready to migrate anytime soon.

If you want to take a look at it, it would be the mako templates in langkit here: https://github.com/AdaCore/langkit/tree/master/langkit/templates/python_api. Any help would of course be welcome 🙂

**Comment by pmderodat** [comment]
Hello Manu,

We were recently able to work on Python3 compatibility: see my last message in #362. I’m closing this for now but don’t hesitate to followup in feeded.

**Comment by briot** [comment]
Good news ! I'll try it soon I think. python2 for langkit is not an issue, since it doesn't impact our own scripts using libadalang.
