### ISSUE TITLE
Python 3 version of libadalang

### ISSUE THREAD

**Issue by afaucon** [AdaCore/libadalang#362]
Hello,

I need to start developing a new tool based on libadalang. It would be a shame to make this new tool in Python 2.7 while this language is doomed to disappear soon.

After having installed the lib with pip:

`$ pip install <prefix>/share/libadalang/python/`

But when I import it, I have this error:

`C:\Users\adrien>python`
`Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import libadalang`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "C:\Programs\Python37-32\lib\site-packages\libadalang\__init__.py", line 68, in <module>`
`    _c_lib = ctypes.cdll.LoadLibrary(_c_lib_path)`
`  File "C:\Programs\Python37-32\lib\ctypes\__init__.py", line 442, in LoadLibrary`
`    return self._dlltype(name)`
`  File "C:\Programs\Python37-32\lib\ctypes\__init__.py", line 364, in __init__`
`    self._handle = _dlopen(self._name, mode)`
`OSError: [WinError 193] %1 is not a valid Win32 application`

Note: libadalang.dll that is trying to be opened exists in my PATH env variable.

Is there a python version 3 of libadalang? If no, is such a version coming soon?

**Comment by Roldak** [comment]
Hi,

To answer your first question, we do have plans to migrate the libadalang Python API to Python 3, but it will be for the next release unfortunately (21.0).

As for your issue, it looks like you have a 64bits binary of libadalang but you are trying to use the Python API from a 32bits Python distribution. Could you confirm? e.g by running in your python interpreter the following:
```
import platform
print(platform.architecture())
```
Thanks,

Romain

**Comment by afaucon** [comment]
Ok thanks a lot!
Waiting one more year then...

And my problem is more linked to the mismatch between python 32 bits and libadalag 64bits... Hence it is the opportunity to update to the new python 3.8, 64 bits this time.

Regards,
Adrien

**Comment by pmderodat** [comment]
Hello @afaucon,

No need to wait for one year. :-) We have recently started to add Python3 compatibility to the generated Python bindings. That’s only the for `libadalang` Python package: for now you still need Python2 in order to use Langkit, i.e. to generate Libadalang.

Even though we have minor enhancements in mind, we are nearly done with this effort. The Python bindings should already be usuable using Libadalang and Langkit’s `master` branches.

I’ll close this issue for now, but don’t hesitate to give us feedback if things don’t work for you!
Thank you in advance,
