### ISSUE TITLE
User manual: the Ada API

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#573]
Near the beginning of section 5.2,
>As the previous section says, the first thing to do in order to use Libadalang is to create an analysis context:

We are in section 5, the section referred to is section 3.

My `lal_test.gpr` starts
```
with "/Users/simon/local/libadalang/share/gpr/libadalang";
with "/Users/simon/local/libadalang/share/gpr/langkit_support";

project LAL_Test is
```
... of course, I could set the scenario variable `GPR_PROJECT_PATH` (can I do this in Studio? or would I need an aggregate project?)

Building the project, I get
```
$ gprbuild
using project file lal_test.gpr
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "gnatcoll_gmp"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "gnatcoll"
...
```
which needs `LIBRARY_TYPE=relocatable`.

But more seriously, compiling the program in section 5.2.1 gives
```
main.adb:28:26: no selector "Debug_Text" for type "Ada_Node'Class" defined at libadalang-analysis.ads:73
```
`Debug_Text` is referred to in 5.2, and used here and in 5.3.2.

**Comment by pmderodat** [comment]
Hello @simonjwright,

Thank you for reporting these issues.

It’s very likely that you get this GPRbuild error because you built and installed Libadalang as a shared library only, whereas GPR project files from AdaCore are supposed to use static libs by default. The `manage.py` script builds and installs only shared libraries by default for developper convenience (faster builds, shared libs being necessary to use Python bindings), but this optimization is probably not worth it for regular users.

So let’s update the documentation so that all library flavors are built/installed: just following the documentation should work fine after that. We’ll also update the obsolete `Debug_Text` example. Thanks!
