### ISSUE TITLE
Build failed: value "relocatable" is illegal for typed string "build"

### ISSUE THREAD

**Issue by dinkelk** [AdaCore/libadalang#58]
Hi there,

I am interested in trying out this library, but I am having trouble building it following the instructions in the README.md. I can successfully generate the source code, but compilation fails with an error I am unable to resolve:

```
$ python ada/manage.py make
Generating source for libadalang...
Compiling the grammar...
Compiling properties...
Prepare code emission...
File setup...
Generating sources...
Compiling the quex lexer specification
Generation complete!
Building the generated source code
gnatcoll.gpr:12:04: value "relocatable" is illegal for typed string "build"
gprbuild: "/home/vagrant/libadalang_src/libadalang/build/lib/gnat/libadalang.gpr" processing failed
Build failed: error while running gprbuild -p -j3 -P/home/vagrant/libadalang_src/libadalang/build/lib/gnat/libadalang.gpr -XBUILD_MODE=dev -XLIBRARY_TYPE=relocatable -XXMLADA_BUILD=relocatable -XLIBADALANG_WARNINGS=true:
    Command '['gprbuild', '-p', '-j3', '-P/home/vagrant/libadalang_src/libadalang/build/lib/gnat/libadalang.gpr', '-XBUILD_MODE=dev', '-XLIBRARY_TYPE=relocatable', '-XXMLADA_BUILD=relocatable', '-XLIBADALANG_WARNINGS=true']' returned non-zero exit status 4
```

Any ideas? I am working off the current master branch.

**Comment by DuncanSands** [comment]
Hi Kevin,

> I am interested in trying out this library, but I am having trouble building it 
> following the instructions in the README.md. I can successfully generate the 
> source code, but compilation fails with an error I am unable to resolve:

I'm using the attached script to build (it's a tweaked version of the one that 
comes with the project).  IIRC, the trick that solves your problem is to use 
--enable-build=Production when configuring GNATCOLL.  Anyway, here's what the 
script does

./configure --prefix="$INSTALL_DIR" \
     --enable-build=Production --enable-shared --enable-projects

Best wishes, Duncan.

#! /bin/bash

set -x
set -e

# This script is a helper to get a quick user/developper Libadalang setup.
# Please see the following section for specific settings you need to do before
# running it.

##############################################################
# Change the above with your favorite installation directory #
##############################################################

INSTALL_DIR=$HOME/tmp/tmp/install
export PATH=/opt/gnatpro-18.0/bin/:$PATH

# Install a GNAT Pro or GNAT GPL release for your platform in $INSTALL_DIR (see
# https://libre.adacore.com/ for GPL releases). Then, get the corresponding
# version of GNATCOLL. For instance, GNATCOLL GPL 2017:

#wget -O gnatcoll-gpl-2017-src.tar.gz \
#    http://mirrors.cdn.adacore.com/art/591c45e2c7a447af2deed016
tar xf gnatcoll-gpl-2017-src.tar.gz
rm -rf gnatcoll
mv gnatcoll-gpl-2017-src gnatcoll

#############################################
## The following should work out of the box #
#############################################

export PATH="$INSTALL_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$INSTALL_DIR/lib:$PATH"

# Build GNATCOLL and install it in $INSTALL_DIR
cd gnatcoll
./configure --prefix="$INSTALL_DIR" \
    --enable-build=Production --enable-shared --enable-projects
make PROCESSORS=0
make install
cd ..
export GPR_PROJECT_PATH=$INSTALL_DIR/lib/gnat

# Get Quex
wget -N -O quex-0.65.4.zip "https://downloads.sourceforge.net/project/quex/HISTORY/0.65/quex-0.65.4.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fquex%2Ffiles%2FHISTORY%2F0.65%2F&ts=1484909333&use_mirror=heanet"
export QUEX_PATH="$PWD/quex-0.65.4"
rm -fr "$QUEX_PATH"
unzip quex-0.65.4.zip

# Now prepare the construction of Libadalang itself
rm -fr libadalang
git clone https://github.com/AdaCore/libadalang.git
cd libadalang

# Create a Python virtualenv and install the Libadalang code generation
# dependencies.
#virtualenv lal-venv
#. lal-venv/bin/activate
pip install -r REQUIREMENTS.dev

# Finally generate Libadalang, build it and install it!
ada/manage.py make
ada/manage.py install "$INSTALL_DIR"

# Make the Python binding available
if [ -z "$PYTHONPATH" ]
then
    export PYTHONPATH="$INSTALL_DIR/python"
else
    export PYTHONPATH="$INSTALL_DIR/python:$PYTHONPATH"
fi

# You are ready to run Python scripts using Libadalang!
python -c 'import libadalang; print libadalang'

**Comment by dinkelk** [comment]
Absolutely beautiful. Thank you Duncan, that worked like a charm!
