### ISSUE TITLE
pragma Assert is not handled

### ISSUE THREAD

**Issue by ludogauthier** [AdaCore/libadalang#60]
Hello,

I'm not sure resolution for overloaded operators are implemented yet.
What API call should we make to resolve overloaded operators ?
In python I tried to get the property p_referenced_decl on "BinOp" or "OpPlus" nodes but it raised an exception or returned null.

```
procedure Test_Operator_Overloading is
    type T is new Integer;
    function "+"(A,B: T) return T is (A*B);
begin
    Pragma Assert(T(35) + T(64) = T(35*64));
end Test_Operator_Overloading ;
```

Thanks.

**Comment by raph-amiard** [comment]
Hello Ludovic,

The problem here is that pragma Assert is not handled for the moment (I will hence repurpose the issue).

If you modify your program the following way:

~~~ada
procedure Test_Operator_Overloading is
    type T is new Integer;
    function "+"(A,B: T) return T is (A*B);
    Test : Boolean;
begin
    Test := (T(35) + T(64) = T(35*64));
end Test_Operator_Overloading ;
~~~

You can then get a reference to the overloaded operator by doing p_referenced_decl on the BinOp node.

**Comment by ludogauthier** [comment]
Great news ! Thanks for the solution. Assert support is less important for me at the moment.

**Comment by raph-amiard** [comment]
@ludogauthier Implemented it anyway :)
