### ISSUE TITLE
Python API tutorial fails with "dereferencing a null access"

### ISSUE THREAD

**Issue by jgueytat** [AdaCore/libadalang#905]
![libadalang_PythonTutorial](https://user-images.githubusercontent.com/1152718/147296128-5907f3af-4394-4550-a071-eaa9ace2fd82.png)

While following the [Python API Tutorial](https://docs.adacore.com/live/wave/libadalang/html/libadalang_ug/python_api_tutorial.html) I get an excpetion.

PS C:\Users\gueytaj> gnatls.exe --version
GNATLS Pro 21.2 (20210531-93)
Copyright (C) 1992-2021, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
See your AdaCore support agreement for details of warranty and support.
If you do not have a current support agreement, then there is absolutely
no warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

**Comment by jgueytat** [comment]
If I replace LAL by Libadalang.Analysis in the adb file I don't get the exception.

```
== main.adb ==
Line 35: 'Context : constant Libadalang.Analysis.Analysis_Context := Libadalang.Analysis.Create_Context;'    
Line 40: 'Filename : constant String := Ada.Command_Line.Argument (I);' type is: 'type String is array (Positive range <>) of Character;'
Line 41: 'Unit     : constant Libadalang.Analysis.Analysis_Unit :=\r\n            Context.Get_From_File (Filename);'
```

**Comment by Roldak** [comment]
Hi,

I think this is because you are running the python script without a project file and thus Libadalang cannot find the dependencies of your ada file (Libadalang in this case).
Try adding:
```
with "libadalang";
project Prj is
end Prj;
```
And then running your script again with:
```
python main.py -P prj.gpr my_ada_file.adb
```
This should work if libadalang.gpr is in your `GPR_PROJECT_PATH`

I'll close this issue, feel free to reopen it you're still having issues!

Romain
